name: Run Redis Keep-Alive Script

on:
  schedule:
    - cron: '0 0 */10 * *'  
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  run-redis-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Instalar dependências
        run: npm install ioredis

      - name: Executar script
        run: node keepRedisAlive.js 
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }} 
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }} 
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
